### ISSUE TITLE
Test with different random states instead of k-fold

### ISSUE THREAD

**Issue by weisske** [Speedfan94/PDS_Project#107]
Make random state a parameter and create a test which iterates over x different random states.

**Comment by weisske** [comment]
Would close #71 and #76

**Comment by weisske** [comment]
Example:
State 42:
NN_Regression_Training Training loss - Error Metrics:
RMSE: 6.720150272544825 MAE: 4.199080106086288 R^2: 0.19985749197477753

NN_Regression_Validation Training loss - Error Metrics:
RMSE: 6.770551236550273 MAE: 4.238851188809572 R^2: 0.18044354914298932

NN_Regression Testing loss - Error Metrics:
RMSE: 6.7483388172539245 MAE: 4.220202186318971 R^2: 0.18467474479177226

**Comment by Speedfan94** [comment]
**State 1:**
NN_Regression_Training Training loss - Error Metrics:
RMSE: 6.53591739766718 MAE: 4.1268575131292 R^2: 0.24350861236051058

NN_Regression_Validation Training loss - Error Metrics:
RMSE: 6.609363680211004 MAE: 4.182757360430431 R^2: 0.21927573024661406

NN_Regression Testing loss - Error Metrics:
RMSE: 6.58093865919871 MAE: 4.168917705774114 R^2: 0.22380143523092422


**State 2:**
NN_Regression_Training Training loss - Error Metrics:
RMSE: 6.3993433989372965 MAE: 3.9471211464815084 R^2: 0.2699744748823574

NN_Regression_Validation Training loss - Error Metrics:
RMSE: 6.425850309104389 MAE: 3.974943251642694 R^2: 0.25485666650326544

NN_Regression Testing loss - Error Metrics:
RMSE: 6.527896863064262 MAE: 4.03468512548497 R^2: 0.24944553763196953



**State 5**
NN_Regression_Training Training loss - Error Metrics:
RMSE: 6.428883476059795 MAE: 3.9470728691232195 R^2: 0.26591764409698193

NN_Regression_Validation Training loss - Error Metrics:
RMSE: 6.507258802712747 MAE: 4.004407024806531 R^2: 0.24117085836823782

NN_Regression Testing loss - Error Metrics:
RMSE: 6.505802821117929 MAE: 4.0024931440073335 R^2: 0.246525531417775



**State 8**
NN_Regression_Training Training loss - Error Metrics:
RMSE: 6.4560086189312 MAE: 3.8854191266982463 R^2: 0.2606673720588196

NN_Regression_Validation Training loss - Error Metrics:
RMSE: 6.48851087300372 MAE: 3.9153902486801058 R^2: 0.2344469939622933

NN_Regression Testing loss - Error Metrics:
RMSE: 6.568268577038463 MAE: 3.9456692562072346 R^2: 0.23764840809631238

**State 11**
NN_Regression_Training Training loss - Error Metrics:
RMSE: 6.517596264226434 MAE: 4.038518987171344 R^2: 0.2472302664827225

NN_Regression_Validation Training loss - Error Metrics:
RMSE: 6.612989104118171 MAE: 4.12673427725422 R^2: 0.2138617032815523

NN_Regression Testing loss - Error Metrics:
RMSE: 6.633329530901888 MAE: 4.100175457301521 R^2: 0.21533963099344544


**State 18**
NN_Regression_Training Training loss - Error Metrics:
RMSE: 6.4203157844954974 MAE: 3.907541088750476 R^2: 0.262099635485595

NN_Regression_Validation Training loss - Error Metrics:
RMSE: 6.576520446804231 MAE: 3.9503290987622997 R^2: 0.24521219717694354

NN_Regression Testing loss - Error Metrics:
RMSE: 6.498378237875191 MAE: 3.963669005541874 R^2: 0.24467762526902526

**State 24**
NN_Regression_Training Training loss - Error Metrics:
RMSE: 6.4640324575988934 MAE: 4.018280791612878 R^2: 0.2586846091541867

NN_Regression_Validation Training loss - Error Metrics:
RMSE: 6.59419007638223 MAE: 4.110477196886441 R^2: 0.234383719116378

NN_Regression_Training Training loss - Error Metrics:
RMSE: 6.4640324575988934 MAE: 4.018280791612878 R^2: 0.2586846091541867

**Comment by weisske** [comment]
Done
