### ISSUE TITLE
trip-data // kick out start entries without end

### ISSUE THREAD

**Issue by MaxStroh** [Speedfan94/PDS_Project#11]
**Steps to reproduce:**

1. Open terminal
2. Create Trip Data DF (to be done)
3. Inspect some data entries (of a specific bike, sorted by datetime e.g.)

**Actual behaviour:**

- There are some start entries in the timeline which do not have end entries after it
- The next entry following is a start entry again (does not make sense)

**Expected behaviour:**

- The first start entry should stay, all start entries following without an end entry in-between should be cancelled out

**Possible solution(s) / ideas to work on:**

- Currently none...

**Comment by Speedfan94** [comment]
I think this is done from Kevin in the new function.
We should explore and verify that.

**Comment by MaxStroh** [comment]
feat/datapreparation will fix this issues
