### ISSUE TITLE
check beginning and ending of trip data

### ISSUE THREAD

**Issue by MaxStroh** [Speedfan94/PDS_Project#20]
We should check if our df begins with a start entry and ends with an end entry!
This should happen **before validating and kicking out duplicated starts / ends**!!!

**Comment by weisske** [comment]
@MaxStroh this should be your check of valid start and valid end...
Please close it if thats right.

**Comment by MaxStroh** [comment]
Nope! :)
I can take care about this, but this issue was for something else:
We wanted to include an additional check whether our whole dataset begins with an start and ends with an end.
My algorithm just builds a dataframe with alternating starts and ends :)
