### ISSUE TITLE
Task 3a: Predicting journey duration

### ISSUE THREAD

**Issue by MaxStroh** [Speedfan94/PDS_Project#41]
**Task:**
Predict the journey duration. You may use any Start information in the data set. Also consider
creating new features that may help prediction quality (Hint: In the coding week, we discussed
creating polynomial features. How would you engineer features for periodic quantities with known
period lengths, e.g, a day, a year, ...?).

**Comment by weisske** [comment]
Done. Only fine tuning needed.
=> see new issue
