### ISSUE TITLE
Comment methods by docstring

### ISSUE THREAD

**Issue by weisske** [Speedfan94/PDS_Project#45]
The methods need to be documented. Down below is an example of how to... I will create the pattern and push it from branch doc/methods to dev.

def plz_end(df):
    **"""Add the corresponding plz to each end long and lat in DataFrame

    Args:
        df (DataFrame): DataFrame of trips
    Returns:
        df (DataFrame): DataFrame of trips with end plz
    """**
    plz_value_def()

    df['plz_end'] = df.apply(lambda x: get_plz(x['Latitude_end'], x['Longitude_end']), axis=1)
    return df

**Comment by MaxStroh** [comment]
On methods right now all docstring are done. Other ticket open to finally check docstrings
