### ISSUE TITLE
Create Utils method for datetime casting to int

### ISSUE THREAD

**Issue by weisske** [Speedfan94/PDS_Project#51]
**1. Create utils method like that**

def cast_datetime(pDf):
    pDf["Start Time"] = pd.to_datetime(pDf["Start Time"], format="%Y-%m-%d %H:%M:%S").values.astype(int)
    pDf["End Time"] = pd.to_datetime(pDf["End Time"], format="%Y-%m-%d %H:%M:%S").values.astype(int)

    return pDf

**2. Call this method instead of reimplement this code each time**

**Comment by MaxStroh** [comment]
Ah I now see that you cast the datetime as int - i didn't do that in datapreparation, but i would nevertheless recommend to build a utils method which casts strings to datetime objects.

you could then call this method and do the casting to int on top i would suggest?!
