### ISSUE TITLE
FINAL CHECK: docstring, commentaries & todo's

### ISSUE THREAD

**Issue by mulko93** [Speedfan94/PDS_Project#60]
The docstrings and commentaries should be reviewed and complemented befor final delivery if necessary

**Comment by MaxStroh** [comment]
We should also check for TODOs in the code!

**Comment by MaxStroh** [comment]
We should check for single quotes in the end again!

**Comment by MaxStroh** [comment]
Last unused imports and docstring fixes are committed to branch "42".
