### ISSUE TITLE
Try to predict two models for splitted trip data

### ISSUE THREAD

**Issue by weisske** [Speedfan94/PDS_Project#69]
High MAE and RMSE could arise from long trip durations which are not classified as noise.

Long durations lead to higher errors than short ones when calculating prediction loss.
1. Split the data in long and short trips e.g. <=5 min and >5min.
2. Train one model for each trip type. 

Question how to know which model to use when a trip starts...

**Comment by mulko93** [comment]
Notice about MAE & RMSE in report for further research / bussiness idea

**Comment by MaxStroh** [comment]
Final decission in live session: We do only mention this in report and do not implement this.
