### ISSUE TITLE
Using k-fold

### ISSUE THREAD

**Issue by mulko93** [Speedfan94/PDS_Project#71]
Use k-fold cross validation instead of simple split

**Comment by MaxStroh** [comment]
As overfitting is not that big in our case, k-fold might not bring that much advantage. But we should consider testing it.

**Comment by weisske** [comment]
Take a look at #107 . There instead of folds, whole train, test, val split is used. 
This could be done because of enough computational power and not that big models. Therefore computation time is not a factor.

**Comment by weisske** [comment]
Done
