### ISSUE TITLE
Additional plotting

### ISSUE THREAD

**Issue by mulko93** [Speedfan94/PDS_Project#73]
Plot addtional graphs for report if neccessary

**Comment by MaxStroh** [comment]
Plots to make:
* PieChart (Weekend vs Weekday)
* Average duration per Hour of Day by Weekday
* Average duration per hour of day by season
* PCA: % of explained variance per component

Optional:
* regression on duration of some specific features (to define: which ones?!)

**Comment by MaxStroh** [comment]
Opened new issues for some specific plots: #95 #86

**Comment by weisske** [comment]
PCA Bar plot is done with merge of #105
