### ISSUE TITLE
Docstring + check if everything is needed of method get_data_path()

### ISSUE THREAD

**Issue by weisske** [Speedfan94/PDS_Project#75]
# TODO: Add docstring
def get_data_path():

    if os.path.isdir(os.path.join(os.getcwd(), 'data')):
        return os.path.join(os.getcwd(), 'data')
    elif os.path.isdir(os.path.join(os.getcwd(), "../data")):
        return os.path.join(os.getcwd(), "../data")
    elif os.path.isdir(os.path.join(os.getcwd(), "nextbike/data")):
        return os.path.join(os.getcwd(), "nextbike/data")
    else:
        raise FileNotFoundError

**Comment by Speedfan94** [comment]
Done in feat/docstrings
method is necessary and checks path depending location from where it is called.
